# Generated by Django 2.2.7 on 2019-12-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('all_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('information', models.TextField()),
                ('number_of_shares', models.IntegerField()),
                ('presence', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('operating_income', models.IntegerField()),
                ('operation_expenses', models.IntegerField()),
                ('net_income', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IncomeStatement', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('current_liabilities', models.IntegerField()),
                ('long_term_liabilities', models.IntegerField()),
                ('equity', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Balance', to='company.Company')),
            ],
        ),
    ]
